### ISSUE TITLE
Opam website has no HTTP->HTTPS redirect

### ISSUE THREAD

**Issue by yawaramin** [ocaml-opam/opam2web#178]
Hello, http://opam.ocaml.org/ –can a certificate be added here? Was there one in the past?

**Comment by rjbou** [comment]
Moved this issue to opam2web. Thanks for the report.

**Comment by yawaramin** [comment]
I'd also recommend using the HSTS header to try to force browsers to use HTTPS as much as possible https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
