### ISSUE TITLE
Use opam-repository's repo file as a base instead of re-creating one from scratch

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml-opam/opam2web#235]
Mentioned in https://github.com/ocaml/opam-repository/issues/25961#issuecomment-2138059279
Currently opam2web overwrites the `repo` file to use its own, however opam-repository should be able to make some changes (such as adding a `messages` field) as it being reflected in opam.ocaml.org

**Comment by hannesm** [comment]
See #234
